/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RailRouteImport } from './routes/rail'
import { Route as RegionRouteImport } from './routes/region'
import { Route as ResortsRouteImport } from './routes/resorts'
import { Route as SailingsRouteImport } from './routes/sailings'
import { Route as SkiRouteImport } from './routes/ski'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as InPortRegionRouteImport } from './routes/in-port/$region'
import { Route as LinesIndexRouteImport } from './routes/lines/index'
import { Route as LinesSlugRouteImport } from './routes/lines/$slug'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PoliciesDocRouteImport } from './routes/policies/$doc'
import { Route as PortsIndexRouteImport } from './routes/ports/index'
import { Route as PortsRegionRouteImport } from './routes/ports/$region'
import { Route as PromotionsSlugRouteImport } from './routes/promotions/$slug'
import { Route as RailIndexRouteImport } from './routes/rail/index'
import { Route as RailSlugRouteImport } from './routes/rail/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RailRoute = RailRouteImport.update({
  id: '/rail',
  path: '/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortsRoute = ResortsRouteImport.update({
  id: '/resorts',
  path: '/resorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SailingsRoute = SailingsRouteImport.update({
  id: '/sailings',
  path: '/sailings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkiRoute = SkiRouteImport.update({
  id: '/ski',
  path: '/ski',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InPortRegionRoute = InPortRegionRouteImport.update({
  id: '/in-port/$region',
  path: '/in-port/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesIndexRoute = LinesIndexRouteImport.update({
  id: '/lines/',
  path: '/lines/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesSlugRoute = LinesSlugRouteImport.update({
  id: '/lines/$slug',
  path: '/lines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesDocRoute = PoliciesDocRouteImport.update({
  id: '/policies/$doc',
  path: '/policies/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsIndexRoute = PortsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortsRoute,
} as any)
const PortsRegionRoute = PortsRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => PortsRoute,
} as any)
const PromotionsSlugRoute = PromotionsSlugRouteImport.update({
  id: '/promotions/$slug',
  path: '/promotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RailIndexRoute = RailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RailRoute,
} as any)
const RailSlugRoute = RailSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/itineraries': typeof ItinerariesRoute
  '/ports': typeof PortsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/rail': typeof RailRouteWithChildren
  '/region': typeof RegionRoute
  '/resorts': typeof ResortsRoute
  '/sailings': typeof SailingsRoute
  '/ski': typeof SkiRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/in-port/$region': typeof InPortRegionRoute
  '/lines/$slug': typeof LinesSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/ports/$region': typeof PortsRegionRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/rail/$slug': typeof RailSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/ports/': typeof PortsIndexRoute
  '/rail/': typeof RailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/itineraries': typeof ItinerariesRoute
  '/quote': typeof QuoteRoute
  '/region': typeof RegionRoute
  '/resorts': typeof ResortsRoute
  '/sailings': typeof SailingsRoute
  '/ski': typeof SkiRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/in-port/$region': typeof InPortRegionRoute
  '/lines/$slug': typeof LinesSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/ports/$region': typeof PortsRegionRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/rail/$slug': typeof RailSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/lines': typeof LinesIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/ports': typeof PortsIndexRoute
  '/rail': typeof RailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/itineraries': typeof ItinerariesRoute
  '/ports': typeof PortsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/rail': typeof RailRouteWithChildren
  '/region': typeof RegionRoute
  '/resorts': typeof ResortsRoute
  '/sailings': typeof SailingsRoute
  '/ski': typeof SkiRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/in-port/$region': typeof InPortRegionRoute
  '/lines/$slug': typeof LinesSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/ports/$region': typeof PortsRegionRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/rail/$slug': typeof RailSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/ports/': typeof PortsIndexRoute
  '/rail/': typeof RailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/itineraries'
    | '/ports'
    | '/quote'
    | '/rail'
    | '/region'
    | '/resorts'
    | '/sailings'
    | '/ski'
    | '/destinations/$slug'
    | '/in-port/$region'
    | '/lines/$slug'
    | '/policies/$doc'
    | '/ports/$region'
    | '/promotions/$slug'
    | '/rail/$slug'
    | '/destinations/'
    | '/lines/'
    | '/policies/'
    | '/ports/'
    | '/rail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/itineraries'
    | '/quote'
    | '/region'
    | '/resorts'
    | '/sailings'
    | '/ski'
    | '/destinations/$slug'
    | '/in-port/$region'
    | '/lines/$slug'
    | '/policies/$doc'
    | '/ports/$region'
    | '/promotions/$slug'
    | '/rail/$slug'
    | '/destinations'
    | '/lines'
    | '/policies'
    | '/ports'
    | '/rail'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/itineraries'
    | '/ports'
    | '/quote'
    | '/rail'
    | '/region'
    | '/resorts'
    | '/sailings'
    | '/ski'
    | '/destinations/$slug'
    | '/in-port/$region'
    | '/lines/$slug'
    | '/policies/$doc'
    | '/ports/$region'
    | '/promotions/$slug'
    | '/rail/$slug'
    | '/destinations/'
    | '/lines/'
    | '/policies/'
    | '/ports/'
    | '/rail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  ItinerariesRoute: typeof ItinerariesRoute
  PortsRoute: typeof PortsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  RailRoute: typeof RailRouteWithChildren
  RegionRoute: typeof RegionRoute
  ResortsRoute: typeof ResortsRoute
  SailingsRoute: typeof SailingsRoute
  SkiRoute: typeof SkiRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  InPortRegionRoute: typeof InPortRegionRoute
  LinesSlugRoute: typeof LinesSlugRoute
  PoliciesDocRoute: typeof PoliciesDocRoute
  PromotionsSlugRoute: typeof PromotionsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  LinesIndexRoute: typeof LinesIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rail': {
      id: '/rail'
      path: '/rail'
      fullPath: '/rail'
      preLoaderRoute: typeof RailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region': {
      id: '/region'
      path: '/region'
      fullPath: '/region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resorts': {
      id: '/resorts'
      path: '/resorts'
      fullPath: '/resorts'
      preLoaderRoute: typeof ResortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sailings': {
      id: '/sailings'
      path: '/sailings'
      fullPath: '/sailings'
      preLoaderRoute: typeof SailingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ski': {
      id: '/ski'
      path: '/ski'
      fullPath: '/ski'
      preLoaderRoute: typeof SkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-port/$region': {
      id: '/in-port/$region'
      path: '/in-port/$region'
      fullPath: '/in-port/$region'
      preLoaderRoute: typeof InPortRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/': {
      id: '/lines/'
      path: '/lines'
      fullPath: '/lines/'
      preLoaderRoute: typeof LinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$slug': {
      id: '/lines/$slug'
      path: '/lines/$slug'
      fullPath: '/lines/$slug'
      preLoaderRoute: typeof LinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$doc': {
      id: '/policies/$doc'
      path: '/policies/$doc'
      fullPath: '/policies/$doc'
      preLoaderRoute: typeof PoliciesDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports/': {
      id: '/ports/'
      path: '/'
      fullPath: '/ports/'
      preLoaderRoute: typeof PortsIndexRouteImport
      parentRoute: typeof PortsRoute
    }
    '/ports/$region': {
      id: '/ports/$region'
      path: '/$region'
      fullPath: '/ports/$region'
      preLoaderRoute: typeof PortsRegionRouteImport
      parentRoute: typeof PortsRoute
    }
    '/promotions/$slug': {
      id: '/promotions/$slug'
      path: '/promotions/$slug'
      fullPath: '/promotions/$slug'
      preLoaderRoute: typeof PromotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rail/': {
      id: '/rail/'
      path: '/'
      fullPath: '/rail/'
      preLoaderRoute: typeof RailIndexRouteImport
      parentRoute: typeof RailRoute
    }
    '/rail/$slug': {
      id: '/rail/$slug'
      path: '/$slug'
      fullPath: '/rail/$slug'
      preLoaderRoute: typeof RailSlugRouteImport
      parentRoute: typeof RailRoute
    }
  }
}

interface PortsRouteChildren {
  PortsRegionRoute: typeof PortsRegionRoute
  PortsIndexRoute: typeof PortsIndexRoute
}

const PortsRouteChildren: PortsRouteChildren = {
  PortsRegionRoute: PortsRegionRoute,
  PortsIndexRoute: PortsIndexRoute,
}

const PortsRouteWithChildren = PortsRoute._addFileChildren(PortsRouteChildren)

interface RailRouteChildren {
  RailSlugRoute: typeof RailSlugRoute
  RailIndexRoute: typeof RailIndexRoute
}

const RailRouteChildren: RailRouteChildren = {
  RailSlugRoute: RailSlugRoute,
  RailIndexRoute: RailIndexRoute,
}

const RailRouteWithChildren = RailRoute._addFileChildren(RailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  ItinerariesRoute: ItinerariesRoute,
  PortsRoute: PortsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  RailRoute: RailRouteWithChildren,
  RegionRoute: RegionRoute,
  ResortsRoute: ResortsRoute,
  SailingsRoute: SailingsRoute,
  SkiRoute: SkiRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  InPortRegionRoute: InPortRegionRoute,
  LinesSlugRoute: LinesSlugRoute,
  PoliciesDocRoute: PoliciesDocRoute,
  PromotionsSlugRoute: PromotionsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  LinesIndexRoute: LinesIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
